#!/bin/sh
# Automatically generated by EnvyControl


# xrandr --auto
hdmi=$(xrandr -q | grep -w "connected" | grep -v eDP | awk '{print $1}')
if [ "$hdmi" ]; then
  edp=$(xrandr --listactivemonitors | grep -v Monitors | awk '{print $4}')
  xrandr --output "$hdmi" --primary --mode 3840x2160 --pos 2560x0 --rotate normal \
    --output "$edp" --mode 2560x1600 --pos 0x560 --rotate normal
else
  xrandr --auto
fi
  
