gui:
  showIcons: true
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - yellow
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default # set to `default` to have no background colour
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - cyan
